### ISSUE TITLE
Shortcut ctrl-G,ctrl-T leads to two test files for the same code file.

### ISSUE THREAD

**Issue by Tanemanar** [testcop/docs#3]
Hello,

We have classes (and files) with name like XYZ0123456789012345678901234567890123456 (40 characters) and VWXYZ0123456789012345678901234567890123456 (the same with a prefix), we also have unit tests classes  XYZ0123456789012345678901234567890123456Test and  VWXYZ0123456789012345678901234567890123456Test.
When I try to find the tests for the XYZ0123456789012345678901234567890123456 code by using the shortcut, it proposes me a list with XYZ0123456789012345678901234567890123456Test and  VWXYZ0123456789012345678901234567890123456Test. The other cases are correct (from the second code or back from the tests files).
What is wrong ? Is there a way to avoid that (without renaming our classes : ) ) ?

**Comment by testcop** [comment]
closing as I can't reproduce in latest release
